# Generated by Django 5.2.5 on 2025-08-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miopinion',
            name='mensaje',
            field=models.TextField(default='No hay un mensaje aun.'),
        ),
    ]
