# Generated by Django 5.2.5 on 2025-09-12 20:23

from django.db import migrations

def create_superuser(apps, schema_editor):
    User = apps.get_model("auth", "User")
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser(
            username="admin",
            email="admin@example.com",
            password="admin123"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_miopinion_mensaje'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
